### ISSUE TITLE
加菜：阿里云笔试题

### ISSUE THREAD

**Issue by gumingWu** [gumingWu/daily-hand-write#20]
# Promisify
1. 给定⼀个回调形式调⽤的⽹络请求函数request（可直接使⽤，⽆需关⼼具体实现），请将其Promise化，以⽀持形如
```js
promisifiedRequest(params) 
 .then(successCallback) 
 .catch(failCallback);
```
的调⽤⽅式。request的调⽤形式如下：
```js
request({
 params: { id: 1 },
 success: ({ code, data }) => {
// 示例返回：{ code: 200, data: { name: 'Tom' } } 
 console.log(code, data);
 },
 fail: ({ code, message }) => {
 console.log(code, message)
 }
})
```
2.  给定登录态校验⽅法checkLogin: () => boolean（可直接使⽤，⽆需关⼼具体实现）, 在上述实现promisifiedRequest基础上加⼊调⽤鉴权和业务ErrorCode处理逻辑:
    - 未登录(checkLogin返回false时)跳转⾄login.html
    - 400: 弹出提示『参数错误』
    - 404: 跳转到/404.html

# ⾃定义Hook
给定⼀个接⼝调⽤⽅法的定义：
```js
interface Api<T> {
 (p: T): Promise<{ items: any[]; page: number; pageSize: number }>;
}
// 接⼝⼊参定义
interface Params {
 id: number;
 page: number;
 pageSize: number;
}
// ListItems接⼝可以直接使⽤，⽆需关⼼具体实现
const ListItems: Api<Params> = async (
 p: Params,
) => api('/listItems', GET, p);

```
请编写⼀个HookuseItemList并尽可能完善地⽀持：
1. 以{ id: 1, page: 1, pageSize: 10 }为参数初始化列表；
2.  ⽀持改变参数以重新获取列表；
3. 合理设置请求的loading状态；
4. 避免内存泄露；
5. 尽可能保证参数与返回数据的⼀致性，例如当参数page为1时，hook中保存列表的值应保证为第⼀⻚的数据，尽可能避免page变为2时仍缓存了第⼀⻚数据的情况

# 简单Flex应⽤
实现⼀个三列布局以⽀持
1. 左右两列以15%宽度初始化宽度；
2. 左右两列保持定宽；
3.  中间列⾃适应。
4. 注意：不可以指定左右两列的宽度值，如width: 100px;
```html
<div class="container">
 <div class="left">
 Left
 </div>
 <div class="middle">
 Middle
 </div>
 <div class="right">
 Right
 </div>
</div>

```
```css
.container {
height: 400px;
 /* your code here */
}
.left {
 height: 100%;
 border: 1px solid #ccc;
 /* your code here */
}
.middle {
 height: 100%;
 border: 1px solid #ccc;
 /* your code here */
}
.right {
 height: 100%;
 border: 1px solid #ccc;
 /* your code here */
}
```
